---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/file_imports":
    post:
      summary: Import File
      tags:
      - Import
      parameters: []
      responses:
        '200':
          description: File Imported
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: File Imported
                required:
                - message
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file_report[file]:
                  type: string
                  format: binary
                  nullable: false
              required:
              - file_report[file]
  "/api/payroll_reports":
    get:
      summary: Get all time logs
      tags:
      - Payroll Report
      responses:
        '200':
          description: Returns result
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/payrollReportObject"
  "/api/payroll_reports/{report_id}":
    get:
      summary: Get all time logs
      tags:
      - Payroll Report
      parameters:
      - name: report_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns result
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/payrollReportObject"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    errors_object:
      type: object
      properties:
        message:
          type: string
    payrollReportObject:
      properties:
        payrollReport:
          type: object
          properties:
            employeeReports:
              type: array
              items:
                type: object
                properties:
                  employeeId:
                    type: string
                    example: '1'
                  payPeriod:
                    type: object
                    properties:
                      startDate:
                        type: string
                        example: '2020-01-01'
                      endDate:
                        type: string
                        example: '2020-01-05'
                  amountPaid:
                    type: string
                    example: "$300.0"
      required:
      - payrollReport
