---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/file_imports":
    post:
      summary: Import File
      tags:
      - Import
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: params
        in: formData
        type: file
        schema:
          "$ref": "#/components/schemas/uploadObject"
      responses:
        '200':
          description: File Imported
          schema:
            type: object
            properties:
              message:
                type: string
                example: File Imported
            required:
            - message
        '422':
          description: invalid request
          schema:
            "$ref": "#/components/schemas/errors_object"
  "/api/payroll_reports":
    get:
      summary: Get all time logs
      tags:
      - Payroll Report
      produces:
      - application/json
      responses:
        '200':
          description: Returns result
          schema:
            "$ref": "#/components/schemas/payrollReportObject"
  "/api/payroll_reports/{report_id}":
    get:
      summary: Get all time logs
      tags:
      - Payroll Report
      produces:
      - application/json
      parameters:
      - name: report_id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: Returns result
          schema:
            "$ref": "#/components/schemas/payrollReportObject"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: sa-payroll.herokuapp.com
components:
  schemas:
    errors_object:
      type: object
      properties:
        message:
          type: string
    payrollReportObject:
      properties:
        payrollReport:
          type: object
          properties:
            employeeReports:
              type: array
              items:
                type: object
                properties:
                  employeeId:
                    type: string
                    example: '1'
                  payPeriod:
                    type: object
                    properties:
                      startDate:
                        type: string
                        example: '2020-01-01'
                      endDate:
                        type: string
                        example: '2020-01-05'
                  amountPaid:
                    type: string
                    example: "$300.0"
      required:
      - payrollReport
    uploadObject:
      type: object
      properties:
        file_report[file]:
          type: string
          format: binary
      required:
      - file_report[file]
